          let product = [
            {
             id: '1001',
             subject: 'Math',
             location: 'London',
             description: 'Calculus for beginners',
             price: 150.15,
             image: 'assets/math.svg',
             numberOfSpaces: 4
          },
          {
            id: '1002',
            subject: 'Biology',
            location: 'Edinburgh',
            description: 'Mitochondria - Powerhouse of the Cell',
            price: 150.30,
            image: 'assets/dna.svg',
            numberOfSpaces: 8,
          },
            {
            id: '1003',
            subject: 'Chemistry',
            location: 'Cardif',
            description: 'Radioactivity',
            price: 150.50,
            image: 'assets/chemistrymedium.svg',
            numberOfSpaces: 12,
          },
                    {
            id: '1004',
            subject: 'Arts',
            location: 'Dublin',
            description: 'Leonardo Da Vinci',
            price: 101.99,
            image: 'assets/art.svg',
            numberOfSpaces: 16,
          },
                    {
            id: '1005',
            subject: 'Poetry',
            location: 'Dorking',
            description: 'Authors of XX century',
            price: 150.30,
            image: 'assets/poetry.svg',
            numberOfSpaces: 20,
          },
                    {
            id: '1006',
            subject: 'IT',
            location: 'Paris',
            description: 'Office 365 - introduction',
            price: 150.30,
            image: 'assets/it.svg',
            numberOfSpaces: 16,
          },
                    {
            id: '1007',
            subject: 'Robotics',
            location: 'Kent',
            description: 'Raspberry pi & Linux',
            price: 150.30,
            image: 'assets/robot.svg',
            numberOfSpaces: 12,
          },
                    {
            id: '1008',
            subject: 'Geography',
            location: 'Bristol',
            description: 'What is a volcano?',
            price: 150.30,
            image: 'assets/earth.svg',
            numberOfSpaces: 8,
          },
                    {
            id: '1009',
            subject: 'English',
            location: 'Oxford',
            description: 'Past tense',
            price: 150.30,
            image: 'assets/language.svg',
            numberOfSpaces: 4,
          },
                    {
            id: '1010',
            subject: 'Economics',
            location: 'Cambridge',
            description: 'Recession and Banks',
            price: 150.30,
            image: 'assets/economy.svg',
            numberOfSpaces: '2',
          }
        ];